spring:
    activemq:
            broker-url: 'tcp://activemq.prod.com:61616'
            user: xqy
            password: 'JDFfsj^8234'
    redis:
        # Redis服务器地址
        host: r-wz9642fa572f5a24.redis.rds.aliyuncs.com
        # Redis服务器连接端口
        port: 6379
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器连接密码（默认为空
        password: XqyREDIS1314cpt
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 50
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 100

mq: 
    queue:
        wxTemplateQueueName: wxTemplateHandle-prod
  
database: 
    finance:
        url: jdbc:sqlserver://mssql.prod.com:1433;DatabaseName=LZT
        driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: WWW.1314.CoM
